### PR TITLE
rpull: display progress

### PR DESCRIPTION
**Pull request by AkihiroSuda**
```console
$ time sudo ctr-remote  images rpull docker.io/ktokunaga/python:3.7-sgz
fetching sha256:01e0710c... application/vnd.docker.distribution.manifest.v2+json
fetching sha256:f23983eb... application/vnd.docker.container.image.v1+json
INFO[0003] /images/create: {"name":"docker.io/ktokunaga/python:3.7-sgz"} 
INFO[0003] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs"} 
INFO[0006] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:81061705323fa1b7f13da36393d2e432d6afb789b3cbe227debc5bbf0a09a14d"} 
INFO[0006] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs: size=52938701"} 
INFO[0006] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs: opened stargz archive"} 
INFO[0006] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs: got TOCEntry"} 
INFO[0006] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/1/fs"} 
INFO[0007] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs"} 
INFO[0007] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:90e41b5458a4d5f5418a036a98f5e13e1b359c0b0b7c9f41bae3c9ec6ce89deb"} 
INFO[0007] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs: size=7899005"} 
INFO[0007] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs: opened stargz archive"} 
INFO[0007] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs: got TOCEntry"} 
INFO[0007] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/2/fs"} 
INFO[0008] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/3/fs"} 
INFO[0008] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/3/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:152a08db06f625e5d56f20cabec26d724bd4f50b75c82bff738c712a34ac9b7c"} 
INFO[0008] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/3/fs: size=10047578"} 
INFO[0008] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/3/fs: opened stargz archive"} 
INFO[0008] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/3/fs: got TOCEntry"} 
INFO[0008] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/3/fs"} 
INFO[0008] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs"} 
INFO[0009] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:5a5efb0aa72ada62ba989b7181c70806cd459afde940046f1d4008b192d3ea1c"} 
INFO[0009] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs: size=54370097"} 
INFO[0009] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs: opened stargz archive"} 
INFO[0009] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs: got TOCEntry"} 
INFO[0009] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/4/fs"} 
INFO[0009] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs"} 
INFO[0010] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:77ddd817f397c3aed7a3d3770065e7616907e3342e0879bf94c40f256a35a0bf"} 
INFO[0010] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs: size=198131103"} 
INFO[0010] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs: opened stargz archive"} 
INFO[0010] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs: got TOCEntry"} 
INFO[0010] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/5/fs"} 
INFO[0011] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs"} 
INFO[0011] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:03737c61c26c3bbe9f052b5177baa4cc7fe50d8c3d65d3d95d1e60a3cc6bd2f9"} 
INFO[0011] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs: size=6343039"} 
INFO[0011] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs: opened stargz archive"} 
INFO[0011] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs: got TOCEntry"} 
INFO[0011] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/6/fs"} 
INFO[0012] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs"} 
INFO[0012] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:18d6cf2170992837e7824d6efba926129868426cc57e8e057ff769e59a0558e8"} 
INFO[0012] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs: size=26921646"} 
INFO[0012] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs: opened stargz archive"} 
INFO[0012] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs: got TOCEntry"} 
INFO[0012] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/7/fs"} 
INFO[0012] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/8/fs"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/8/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:4772928a75656e0c0b1848a0290db27788844657aa038ba59e1ee256a38a8f94"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/8/fs: size=557"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/8/fs: opened stargz archive"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/8/fs: got TOCEntry"} 
INFO[0013] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/8/fs"} 
INFO[0013] /stargz/mount/begin: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs: resolved URL for ref=docker.io/ktokunaga/python:3.7-sgz, digest=sha256:4c4b7619bf166680197c3353a62a913f100291525f30107dd51a5c95cb127f24"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs: size=2085210"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs: opened stargz archive"} 
INFO[0013] /stargz/log: {"text":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs: got TOCEntry"} 
INFO[0013] /stargz/mount/complete: {"mountpoint":"/var/lib/containerd-stargz-grpc/snapshotter/snapshots/9/fs"} 
real    0m13.912s
user    0m0.158s
sys     0m0.061s
```

c.f.
```console
$ time sudo ctr images pull docker.io/ktokunaga/python:3.7-org
docker.io/ktokunaga/python:3.7-org:                                               resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:ddb23df374f4161b6778d9f995e0504001c438219810779056883e3657797158:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:0ba8c666d52aaaeb855dc294d72e28d446040bbea238058fe59588b9b8e029b6: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:666534959f2b872ef0ab48c348ab613ab31f1fcf4a197880fb1b2015985648c3:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:27622921edb2aae9e0cb64f71a81b4a7cfef8f6a6c766514a018815834ba4e14:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:dcfa0aa1ae2c54d0de4b6ad0ee4d9f795c93368ae7d87801784c1f8ae624ac33:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:de787d71ba24dd961575e0522eee8ef867db8a55bbc1d899bcf8b44c35340087:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:61cf1e8f93852d717dfc9f739d340ef82a7ef43a2d739c8246ea838e5fc9e14e:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:8f0fdd3eaac017684c880d836abdaf02f9db7ac8ecca970356482e3d8e315650:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:d918eaefd9de8a1595f56900fdb8ab65a03d64b1da1078da7c0b0bf6f7552a14:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:a79fc60597da7e0bebd70aaa25f4fb8ab52e884315263738637feae12aa83d44:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:43bf3e3107f525b7dea5b3cdfd15f62666066202105a0aaddbab2a02aefad1f7:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:420e7f9327074ccc00c3993c410a096d785af1bf957b8f7d92c12573717f87ad:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 63.9s                                                                    total:  330.6  (5.2 MiB/s)                                       
unpacking linux/amd64 sha256:ddb23df374f4161b6778d9f995e0504001c438219810779056883e3657797158...
done

real    1m23.825s
user    0m6.690s
sys     0m12.748s
```

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
WIP. Planning to use containerd Events for detailed status.

**Comment by AkihiroSuda** [comment]
CI passing

**Comment by ktock** [comment]
Seems false positive...
```bash
remote_snapshotter_integration    | time="2020-01-29T13:28:25.447746004Z" level=fatal msg="failed to connect to containerd /run/containerd/containerd.sock" error="failed to dial \"/run/containerd/containerd.sock\": context deadline exceeded"
...
remote_snapshotter_integration exited with code 1
```

off-topic:
We need to get exit code from all containers not only `testenv_integration` in our CI. I'll work on it tomorrow.
https://github.com/ktock/stargz-snapshotter/blob/b680245353191f6779261c15fcb24330a8838ba0/script/make.sh#L71

**Comment by AkihiroSuda** [comment]
> I'll work on it tomorrow.

Get some rest, we can work on that later :+1:

**Comment by ktock** [comment]
Please rebase it on #39

**Pull request closed without merging**
